name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: gradlew bootJar
        run: ./gradlew bootJar

      - name: Copy jar to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "./build/libs/*.jar"
          target: "~"
          strip_components: 2

      - name: SSH Commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            # Kill the existing Java process
            pid=$(pgrep -f 'java -jar')
            if [ -n "$pid" ]; then
              kill -9 $pid
            fi
            # Verify if the process was killed
            sleep 2
            if pgrep -f 'java -jar'; then
              echo "Failed to kill the existing Java process."
              exit 1
            fi
            # Run the new jar file and log output
            nohup java -jar *.jar > app.log 2>&1 &
            # Wait a few seconds to allow the app to start
            sleep 5
            # Check if the new process has started
            if ! pgrep -f 'java -jar'; then
              echo "Failed to start the Java application."
              exit 1
            fi
            # Display the log file
            tail -n 100 app.log
          debug: true