name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: gradlew bootJar
        run: ./gradlew bootJar

      - name: copy jar to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "./build/libs/*.jar"
          target: "~"
          strip_components: 2

      - name: SSH Commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            echo "Killing existing Java process..."
            pid=$(pgrep -f 'java -jar')
            if [ -n "$pid" ]; then
              kill -9 $pid
              echo "Java process $pid killed."
            else
              echo "No Java process found."
            fi
            echo "Starting new Java process..."
            nohup java -jar *.jar > app.log 2>&1 &
            echo "Waiting for the app to start..."
            sleep 5
            echo "Checking if the new process has started..."
            if ! pgrep -f 'java -jar'; then
              echo "Failed to start the Java application."
              exit 1
            fi
            echo "Java application started successfully."
            tail -n 100 app.log
